name: Full CICD Pipeline

on:
  push:
    branches:
      - main
      - master
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check current directory
        run: ls 

      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check current directory
        run: ls 

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: build and test with Maven
        run: mvn clean install

      - name: Check directory after build
        run: |
          ls
          ls target

      - name: Sonarqube Scan
        run: mvn sonar:sonar
      
      - name: Configure Maven settings for nexus
        run: |
          mkdir -p ~/.m2
          echo "<settings>\
          <servers>\
              <server>\
                  <id>nexus</id>\
                  <username>admin</username>\
                  <password>admin123</password>\
              </server>\
          </servers>\
          </settings>" > ~/.m2/settings.xml    

      - name: Upload to Nexus
        run: mvn deploy

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Tomcat
        run: scp -o StrictHostKeyChecking=no target/*.war  ec2-user@35.179.94.59:/opt/tomcat9/webapps
    


      


  